AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  springboot-aws-lambda

  Sample SAM Template for springboot-aws-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  SpringbootAwsLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: springboot-aws-lambda
      Handler: dev.alexandreyoshimatsu.Handler::handleRequest
      Runtime: java8
      MemorySize: 128
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          FUNCTION_NAME: orders
      Events:
        SpringbootAwsLambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /SpringbootAwsLambdaApi
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpringbootAwsLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for Springboot Aws Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/SpringbootAwsLambdaApi/"
  SpringbootAwsLambdaFunction:
    Description: "Springboot Aws Lambda Function ARN"
    Value: !GetAtt SpringbootAwsLambdaFunction.Arn
  SpringbootAwsLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Springboot Aws Lambda function"
    Value: !GetAtt SpringbootAwsLambdaFunctionRole.Arn
